### ISSUE TITLE
it can't work the 

### ISSUE THREAD

**Issue by cfanbo** [Polycademy/php_zmq_binaries#2]
php5.3.13
win7 X64
## zeromq-3.2.4

[Tue Oct 01 14:37:18 2013] [notice] Parent: Created child process 9168
PHP Warning:  PHP Startup: Unable to load dynamic library 'd:/wamp/bin/php/php5.3.13/ext/php_zmq.dll' - \xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\xa8\xb5\xc4\xc4\xa3\xbf\xe9\xa1\xa3\r\n in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'd:/wamp/bin/php/php5.3.13/ext/php_zmq.dll'

using php53 dll file,but it cann't work.

**Comment by CMCDragonkai** [comment]
You have try different combinations. Anyway from the error it seems that the zmq.dll is incorrect.

Oh make sure you're using 32 bit WAMP.

Mine worked with the php54.
